import { useState } from 'react';
import { ArrowDown, ArrowRight, CheckCircle2, CircleAlert, Clock3, FileText, Package, ReceiptText, Store, Truck } from 'lucide-react';
import type { Dataset } from './domain';
import { inclusivePrice, jpy } from './analytics';
import { SupplyGraph } from './SupplyGraph';
import { arrivalLabels, delayLabel, isLate, lineAmount, selectSupply, summarizeSupply, supplyDate } from './supply-model';
import type { SupplyPeriod, SupplyShipment } from './supply-model';
import './supply.css';

const orderLabels = { confirmed: '受付済み', completed: '受取完了', cancelled: '取消', delayed: '遅延' };

function ArrivalBadge({ row }: { row: SupplyShipment }) {
  return <span className={`supply-state ${isLate(row) ? 'late' : row.state === 'on-time' ? 'ontime' : ''}`}>{isLate(row) ? <Clock3 size={13}/> : row.state === 'on-time' ? <CheckCircle2 size={13}/> : <CircleAlert size={13}/>} {arrivalLabels[row.state]}</span>;
}

export function Supply({ data }: { data: Dataset }) {
  const [period, setPeriod] = useState<SupplyPeriod>('current');
  const [lateOnly, setLateOnly] = useState(false);
  const [selectedId, setSelectedId] = useState('');
  const [activeLine, setActiveLine] = useState('');
  const rows = selectSupply(data, period);
  const visible = rows.filter(row => !lateOnly || isLate(row));
  const selected = visible.find(row => row.shipment.id === selectedId) ?? visible.find(row => row.impacts.length && row.shipment.storeId === 'STR-04') ?? visible[0];
  const totals = summarizeSupply(rows);
  const selectShipment = (id: string) => { setSelectedId(id); setActiveLine(''); setLateOnly(false); };
  const storeName = (id: string) => data.stores.find(store => store.id === id)?.name ?? id;
  const supplier = data.suppliers.find(row => row.id === selected?.shipment.supplierId);
  const monthLabel = new Intl.DateTimeFormat('ja-JP', { timeZone: data.timezone, year: 'numeric', month: 'long' }).format(new Date(data.asOf));
  const linkedRows = selected?.impacts ?? [];
  const linkedOrders = [...new Map(linkedRows.map(row => [row.order.id, row.order])).values()];
  const relatedFeedback = data.serviceFeedback.filter(row => linkedOrders.some(order => order.id === row.orderId));
  const selectedSummary = selected ? summarizeSupply([selected]) : null;
  const evidence = linkedRows.find(row => row.line.id === activeLine);
  const priorOrder = selected ? data.orders.filter(order => order.storeId === selected.shipment.storeId && order.status === 'completed'
    && order.fulfilledAt && Date.parse(order.fulfilledAt) < Date.parse(selected.shipment.expectedAt)
    && data.orderLines.some(line => line.orderId === order.id && data.products.some(product => product.id === line.productId && product.supplierId === selected.shipment.supplierId)))
    .sort((first, second) => Date.parse(second.fulfilledAt!) - Date.parse(first.fulfilledAt!))[0] : undefined;
  const priorLines = data.orderLines.filter(line => line.orderId === priorOrder?.id && data.products.some(product => product.id === line.productId && product.supplierId === selected?.shipment.supplierId));
  return <div className="supply-workspace">
    <div className="page-heading supply-heading"><div><span className="eyebrow">店舗への入荷 / 注文実績</span><h1>供給と注文</h1></div><label className="supply-period">入荷予定月<select aria-label="入荷予定月" value={period} onChange={event => { setPeriod(event.target.value as SupplyPeriod); setSelectedId(''); setActiveLine(''); }}><option value="current">{monthLabel}</option><option value="all">全履歴</option></select></label></div>
    <div className={`supply-alert${totals.lateCount ? ' has-delay' : ''}`} role="status">{totals.lateCount ? <CircleAlert size={24}/> : <CheckCircle2 size={24}/>}<div><strong>{totals.lateCount ? `${totals.lateCount} 便で入荷遅延が発生` : '入荷遅延の記録はありません'}</strong><p>{totals.lateCount ? `${totals.impactedStoreCount} 店舗に欠品記録。${totals.cancelled.length} 明細の注文取消を確認。` : `対象 ${rows.length} 便`}</p></div><span className="supply-alert-state">{totals.lateCount ? totals.pendingCount ? <><Clock3 size={15}/>{totals.pendingCount} 便が未着</> : <><CheckCircle2 size={15}/>遅延便は到着済み</> : <Truck size={20}/>}</span></div>
    <section className="supply-metrics" aria-label="供給影響の集計"><div><span><Truck size={15}/>遅延した入荷便</span><strong>{totals.lateCount}<small>/ {rows.length} 便</small></strong><span>予定到着と実績を比較</span></div><div><span><Store size={15}/>欠品記録のある店舗</span><strong>{totals.impactedStoreCount}<small>店舗</small></strong><span>入荷便と対象明細の照合済み</span></div><div><span><ReceiptText size={15}/>取消対象</span><strong>{totals.cancelled.length}<small>明細</small></strong><span>{new Set(totals.cancelled.map(row => row.order.id)).size} 注文 / {totals.cancelled.reduce((total, row) => total + row.line.quantity, 0)} 点</span></div><div><span>取消商品額（税抜）</span><strong>{jpy(totals.cancelledAmount)}</strong><span>値引後の商品額・損失額ではありません</span></div></section>
    <div className="supply-workbench">
      <aside className="supply-sidebar" aria-label="入荷便の選択"><div className="section-heading"><h2><Truck size={17}/>入荷便</h2><span>{visible.length} 便</span></div><div className="supply-segments" role="group" aria-label="入荷便の絞り込み"><button aria-pressed={!lateOnly} onClick={() => setLateOnly(false)}>すべて</button><button aria-pressed={lateOnly} onClick={() => setLateOnly(true)}>遅延あり</button></div>
        <div className="supply-shipment-list">{visible.map(row => <button key={row.shipment.id} className={`supply-shipment${selected?.shipment.id === row.shipment.id ? ' selected' : ''}`} aria-pressed={selected?.shipment.id === row.shipment.id} onClick={() => { setSelectedId(row.shipment.id); setActiveLine(''); }}><span className="supply-shipment-name"><strong>{storeName(row.shipment.storeId)}</strong><ArrowRight size={15}/></span><ArrivalBadge row={row}/><span className="supply-shipment-date">予定 {supplyDate(row.shipment.expectedAt)}</span><span className="supply-shipment-bottom"><code>{row.shipment.id}</code>{isLate(row) && <b>+{delayLabel(row.delayHours)}</b>}</span></button>)}</div>
        {!visible.length && <p className="empty">対象の入荷便はありません。</p>}
        {supplier && <div className="supply-supplier"><span>供給会社</span><h3>{supplier.name}</h3><p>{supplier.city}</p><code>{supplier.id}</code></div>}
        {priorOrder && <div className="supply-prior-order"><span>この便より前の受取</span><h3><CheckCircle2 size={16}/>{storeName(priorOrder.storeId)}</h3><time>{supplyDate(priorOrder.fulfilledAt!)}</time><strong>{jpy(priorLines.reduce((total, line) => total + inclusivePrice(lineAmount(line), line.taxPercent), 0))}<small>（税込）</small></strong><p>{priorLines.map(line => `${data.products.find(product => product.id === line.productId)?.name ?? line.productId} / ${line.quantity} 点`).join('、')}</p><span className="supply-state ontime">受取完了</span><code>{priorOrder.id}</code></div>}
      </aside>
      <div className="supply-analysis">{selected ? <>
        <section className="supply-arrival" aria-label="選択した入荷便"><div className="section-heading"><div><span className="eyebrow">{selected.shipment.id}</span><h2>{storeName(selected.shipment.storeId)}への入荷</h2></div><ArrivalBadge row={selected}/></div><div className="supply-arrival-times"><div><span>予定到着</span><strong>{supplyDate(selected.shipment.expectedAt)}</strong></div><div className={`supply-delay-gap${isLate(selected) ? ' late' : ''}`}><span>{isLate(selected) ? `+${delayLabel(selected.delayHours)}` : selected.state === 'on-time' ? '定刻内' : '未確認'}</span><ArrowRight size={21}/></div><div><span>{selected.arrivedAt ? '到着実績' : '到着状況'}</span><strong>{selected.arrivedAt ? supplyDate(selected.arrivedAt) : arrivalLabels[selected.state]}</strong></div></div><p className="supply-reason"><FileText size={14}/>{selected.shipment.reason}</p></section>
        <SupplyGraph data={data} period={period} selectedId={selected.shipment.id} onSelect={selectShipment}/>
        <section className="supply-comparison" aria-label="同じ供給会社の店舗比較"><div className="section-heading"><h2>店舗ごとの影響</h2><span>同じ供給会社</span></div><div className="supply-comparison-list">{rows.filter(row => row.shipment.supplierId === selected.shipment.supplierId).map(row => { const summary = summarizeSupply([row]); return <button key={row.shipment.id} aria-pressed={row.shipment.id === selected.shipment.id} onClick={() => selectShipment(row.shipment.id)}><Store size={16}/><span><strong>{storeName(row.shipment.storeId)}</strong><small>{supplyDate(row.shipment.expectedAt)}</small></span><span className={isLate(row) ? 'supply-danger-text' : ''}>{isLate(row) ? `+${delayLabel(row.delayHours)}` : arrivalLabels[row.state]}</span><b>{summary.cancelled.length ? `取消 ${summary.cancelled.length} 明細` : '取消記録なし'}</b><ArrowRight size={15}/></button>; })}</div></section>
        <section className="supply-orders" aria-label="選択便の注文影響"><div className="section-heading"><h2><ReceiptText size={17}/>対象の注文</h2><span>{selectedSummary?.cancelled.length} 取消明細 / {jpy(selectedSummary?.cancelledAmount ?? 0)}（税抜）</span></div>{linkedRows.length ? <div className="table-scroll"><table><thead><tr><th>注文 / 明細</th><th>商品</th><th>数量</th><th>商品額（税抜）</th><th>状態</th><th>欠品記録</th></tr></thead><tbody>{[...new Map(linkedRows.map(row => [row.line.id, row])).values()].map(({ line, order, impact }) => <tr key={line.id}><td><strong>{order.id}</strong><small>{line.id}</small></td><td>{data.products.find(row => row.id === line.productId)?.name ?? line.productId}<small>{line.productId}</small></td><td>{line.quantity} 点</td><td>{jpy(lineAmount(line))}</td><td><span className={`supply-state${order.status === 'cancelled' ? ' late' : ''}`}>{orderLabels[order.status]}</span></td><td><button className="supply-evidence-button" aria-expanded={activeLine === line.id} onClick={() => setActiveLine(activeLine === line.id ? '' : line.id)}><FileText size={14}/>{supplyDate(impact.shortageAt)}</button></td></tr>)}</tbody></table></div> : <div className="supply-no-impact"><Package size={22}/><div><strong>この便に結び付く欠品・取消の記録はありません</strong><p>{selected.state === 'on-time' ? '入荷実績は定刻内です。' : '到着状況と注文への影響は別々に確認します。'}</p></div></div>}
          {evidence && <div className="supply-evidence"><h3><FileText size={16}/>欠品の根拠</h3><p>{evidence.impact.evidence}</p><dl><div><dt>入荷便</dt><dd>{evidence.impact.shipmentId}</dd></div><div><dt>欠品確認</dt><dd>{supplyDate(evidence.impact.shortageAt)} JST</dd></div><div><dt>対象明細</dt><dd>{evidence.line.id}</dd></div></dl><code>{evidence.impact.id}</code></div>}
        </section>
        <div className="supply-detail-columns"><section className="supply-timeline"><h2><Clock3 size={17}/>入荷と注文の経過</h2><ol>{[{ id: 'expected', at: selected.shipment.expectedAt, label: '到着予定', tone: '' }, ...linkedOrders.map(order => ({ id: order.id, at: order.orderedAt, label: `注文受付 / ${order.id}`, tone: '' })), ...linkedRows.map(row => ({ id: row.impact.id, at: row.impact.shortageAt, label: `欠品確認 / ${row.line.id}`, tone: 'late' })), ...(selected.arrivedAt ? [{ id: 'arrived', at: selected.arrivedAt, label: '店舗に到着', tone: 'ontime' }] : [])].sort((first, second) => Date.parse(first.at) - Date.parse(second.at)).map(event => <li key={event.id} className={event.tone}><time>{supplyDate(event.at)}</time><span>{event.label}</span></li>)}</ol>{!selected.arrivedAt && <p className="scope-note">到着実績は未確認です。</p>}</section><section className="supply-feedback"><h2><ReceiptText size={17}/>注文のサービス評価</h2>{relatedFeedback.length ? relatedFeedback.map(row => <blockquote key={row.id}><span className="supply-feedback-rating">{row.rating}<small> / 5</small></span><p>{row.text}</p><footer><code>{row.orderId}</code><span>{supplyDate(row.publishedAt)}</span></footer></blockquote>) : <p className="scope-note">この便に関連する注文のサービス評価は未登録です。</p>}<a href="#/ops/reviews">顧客の声を見る<ArrowRight size={14}/></a></section></div>
      </> : <p className="empty">該当する入荷便はありません。</p>}</div>
    </div>
    <details className="supply-records"><summary><FileText size={15}/>集計の根拠と入荷記録<ArrowDown size={14}/></summary><p>対象は店舗への入荷です。顧客向け配送ではありません。取消商品額は関連が確認できる取消明細を重複排除し、数量 × 単価 − 値引で計算しています。会計上の損失や返金実績ではありません。</p><p>遅延は予定到着と到着実績の差です。未着便は分析基準時点までの超過時間です。欠品・取消の記録がない店舗について、欠品がなかったとは断定していません。</p><div className="table-scroll"><table><thead><tr><th>入荷便</th><th>店舗</th><th>予定到着</th><th>到着実績</th><th>遅延</th></tr></thead><tbody>{rows.map(row => <tr key={row.shipment.id}><td>{row.shipment.id}</td><td>{storeName(row.shipment.storeId)}</td><td>{supplyDate(row.shipment.expectedAt)}</td><td>{row.arrivedAt ? supplyDate(row.arrivedAt) : '未確認'}</td><td>{row.delayHours === null ? '未確認' : delayLabel(row.delayHours)}</td></tr>)}</tbody></table></div><p>ローカル合成データの関連表示です。Fabric Ontology への照会、発注、取消処理、外部通知は実行していません。</p></details>
  </div>;
}